#List of slots to create or modify.
#See documentation for syntax: https://docs.illusivesoulworks.com/curios/configuration#slot-configuration
#
slots = ["id=hands;size=1", "id=bundle;size=1", "id=charm;size=1"]

